version: "3.8" 

services:
  # API Gateway service
  api-gateway:
    build: ./api-gateway 
    ports:
      - "3000:3000" 
    env_file: ./api-gateway/.env 
    depends_on: 
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  # Identity service
  identity-service:
    build: ./identity-service
    env_file: ./identity-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  # Post service
  post-service:
    build: ./post-service
    env_file: ./post-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  # Media service
  media-service:
    build: ./media-service
    env_file: ./media-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  # Search service
  search-service:
    build: ./search-service
    env_file: ./search-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  # Redis service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379" 

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP port for messaging.
      - "15672:15672" # Management console port.
    healthcheck: # Healthcheck configuration for RabbitMQ.
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"] 
      interval: 30s 
      timeout: 10s 
      retries: 5 
